# Generated by Django 4.1.5 on 2023-04-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_wishlist_wishlistitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_code',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
