# Generated by Django 4.1.5 on 2023-05-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='public/static/default/profile.jpg', upload_to='profile'),
        ),
    ]
