# Generated by Django 4.1.5 on 2023-05-22 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_is_sold'),
        ('accounts', '0020_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_items', to='products.product'),
        ),
    ]
